### ISSUE TITLE
Files indexing.

### ISSUE THREAD

**Issue by luckcolors** [blevesearch/bleve-explorer#1]
Hello!
i need to index files in bleve (not the content but the file and search the file name using the query)
How can i do this?

Also could you add an raw export link at every result? So i can simply export a document by clicking?

**Comment by mschoch** [comment]
Hi,

I'm not exactly sure I understand what you want to index.  Bleve is designed to index Go structures.  The bleve-explorer sample app (where you've filed this bug) is designed to index JSON.  You could have a structure with a singe field like:

```
thingToIndex := struct{
    Filename string `json:"filename"`
}{
    Filename: "/path/to/file"
}
```

Bleve can index this datastructure, and bleve-explorer could work with the JSON serialized version of it.

So you could build another app to crawl the files you want to index, and index this data (either in Go with bleve, or using the REST API of bleve-explorer)

Taking this approach we are not indexing or storing any of the file content in bleve, just the filenames.

I'm not sure what you mean by "add an raw export link at every result".  As bleve-explorer is a general purpose app, it just displays all the fields you have stored.  You could store a link to the file content in bleve, but its just data, bleve-explorer won't give it any special treatment.

Perhaps I'm misunderstanding some or all of what you're asking for.  Please let me know.

**Comment by luckcolors** [comment]
OK here's an example:
I have some files like .png .rar .js .... and i want to index them into bleve just by the filename.(the file content doesn't need to be indexed but just stored in the bleve db) so then by querying the api for a certain filename i can get the file content as the output

**Comment by mschoch** [comment]
Ah, OK.  So everything I said above, only you'd add an additional field to the struct to store the content.

```
thingToIndex := struct{
    Filename string `json:"filename"`
    Content []byte `json:"content"`
}{
    Filename: "/path/to/file",
    Content: \<insert your content here\>,
}
```

Unfortunately, that doesn't quite work yet because we don't support []byte.  There is an open issue for it here:  https://github.com/blevesearch/bleve/issues/100

**Comment by luckcolors** [comment]
ok thanks.
but can i simply make an api call to index a .png file and get it indexed in bleve? Like:
Import a file: PUT /api/{indexName}/{docID} - index document
Export a file: GET /api/{indexName}/{docID}
Where docID is the filename

**Comment by mschoch** [comment]
Something close to that should be possible.  But, then the problem you have is that you want to search on the ID, and currently bleve doesn't let you search on the id.  Thats another bug, I'll open one for it now: https://github.com/blevesearch/bleve/issues/192

So, if we implemented that feature, you'd basically set up a mapping saying you just want to store the entire body content, but also analyze the ID.

This is not our most common use case, but it should be possible to support it.
