### ISSUE TITLE
invalid memory address

### ISSUE THREAD

**Issue by albertog** [blevesearch/bleve-explorer#6]
In my linux debian appear this error when you try to navitage
//trace

2016/01/04 23:16:13 http: panic serving [::1]:36988: runtime error: invalid memory address or nil pointer dereference
goroutine 9 [running]:
net/http.(_conn).serve.func1(0xc820144000, 0x7f94cd544d88, 0xc820030260)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(_AssetFS).Open(0xc8200d3740, 0xc82014c360, 0x11, 0x0, 0x0, 0x0, 0x0)
    /home/albertog/go_path/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0x7f94cc4fd058, 0xc82015a000, 0xc8200e8d20, 0x7f94cd5438a8, 0xc8200d3740, 0xa37008, 0x1, 0x756ea1346ab401)
    /usr/local/go/src/net/http/fs.go:394 +0x5b1
net/http.(_fileHandler).ServeHTTP(0xc8200dc110, 0x7f94cc4fd058, 0xc82015a000, 0xc8200e8d20)
    /usr/local/go/src/net/http/fs.go:483 +0x19c
main.myFileHandler.ServeHTTP(0x7f94cd5438d0, 0xc8200dc110, 0x7f94cc4fd058, 0xc82015a000, 0xc8200e8d20)
    /home/albertog/Downloads/bleve-explorer-master/http_util.go:59 +0xb5
main.(_myFileHandler).ServeHTTP(0xc8200dc1e0, 0x7f94cc4fd058, 0xc82015a000, 0xc8200e8d20)
    <autogenerated>:7 +0xb6
net/http.StripPrefix.func1(0x7f94cc4fd058, 0xc82015a000, 0xc8200e8d20)
    /usr/local/go/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8200d3800, 0x7f94cc4fd058, 0xc82015a000, 0xc8200e8d20)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(_Router).ServeHTTP(0xc820015a90, 0x7f94cc4fd058, 0xc82015a000, 0xc8200e8d20)
    /home/albertog/go_path/src/github.com/gorilla/mux/mux.go:103 +0x270
net/http.(_ServeMux).ServeHTTP(0xc820010a20, 0x7f94cc4fd058, 0xc82015a000, 0xc8200e8d20)
    /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc82012c660, 0x7f94cc4fd058, 0xc82015a000, 0xc8200e8d20)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(_conn).serve(0xc820144000)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(_Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6
2016/01/04 23:16:13 http: panic serving [::1]:36989: runtime error: invalid memory address or nil pointer dereference
goroutine 10 [running]:
net/http.(_conn).serve.func1(0xc8201440b0, 0x7f94cd544d88, 0xc820030268)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(_AssetFS).Open(0xc8200d3740, 0xc82014c700, 0x11, 0x0, 0x0, 0x0, 0x0)
    /home/albertog/go_path/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0x7f94cc4fd058, 0xc82015a2c0, 0xc8200e8e00, 0x7f94cd5438a8, 0xc8200d3740, 0xa37008, 0x1, 0x756ea102ab1001)
    /usr/local/go/src/net/http/fs.go:394 +0x5b1
net/http.(_fileHandler).ServeHTTP(0xc8200dc110, 0x7f94cc4fd058, 0xc82015a2c0, 0xc8200e8e00)
    /usr/local/go/src/net/http/fs.go:483 +0x19c
main.myFileHandler.ServeHTTP(0x7f94cd5438d0, 0xc8200dc110, 0x7f94cc4fd058, 0xc82015a2c0, 0xc8200e8e00)
    /home/albertog/Downloads/bleve-explorer-master/http_util.go:59 +0xb5
main.(_myFileHandler).ServeHTTP(0xc8200dc1e0, 0x7f94cc4fd058, 0xc82015a2c0, 0xc8200e8e00)
    <autogenerated>:7 +0xb6
net/http.StripPrefix.func1(0x7f94cc4fd058, 0xc82015a2c0, 0xc8200e8e00)
    /usr/local/go/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8200d3800, 0x7f94cc4fd058, 0xc82015a2c0, 0xc8200e8e00)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(_Router).ServeHTTP(0xc820015a90, 0x7f94cc4fd058, 0xc82015a2c0, 0xc8200e8e00)
    /home/albertog/go_path/src/github.com/gorilla/mux/mux.go:103 +0x270
net/http.(_ServeMux).ServeHTTP(0xc820010a20, 0x7f94cc4fd058, 0xc82015a2c0, 0xc8200e8e00)
    /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc82012c660, 0x7f94cc4fd058, 0xc82015a2c0, 0xc8200e8e00)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(_conn).serve(0xc8201440b0)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(_Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6
2016/01/04 23:16:13 http: panic serving [::1]:36990: runtime error: invalid memory address or nil pointer dereference
goroutine 18 [running]:
net/http.(_conn).serve.func1(0xc82015a420, 0x7f94cd544d88, 0xc820174010)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(_AssetFS).Open(0xc8200d3740, 0xc820138540, 0x11, 0x0, 0x0, 0x0, 0x0)
    /home/albertog/go_path/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0x7f94cc4fd058, 0xc820144160, 0xc8201cc000, 0x7f94cd5438a8, 0xc8200d3740, 0xa37008, 0x1, 0x756ea17084c301)
    /usr/local/go/src/net/http/fs.go:394 +0x5b1
net/http.(_fileHandler).ServeHTTP(0xc8200dc110, 0x7f94cc4fd058, 0xc820144160, 0xc8201cc000)
    /usr/local/go/src/net/http/fs.go:483 +0x19c
main.myFileHandler.ServeHTTP(0x7f94cd5438d0, 0xc8200dc110, 0x7f94cc4fd058, 0xc820144160, 0xc8201cc000)
    /home/albertog/Downloads/bleve-explorer-master/http_util.go:59 +0xb5
main.(_myFileHandler).ServeHTTP(0xc8200dc1e0, 0x7f94cc4fd058, 0xc820144160, 0xc8201cc000)
    <autogenerated>:7 +0xb6
net/http.StripPrefix.func1(0x7f94cc4fd058, 0xc820144160, 0xc8201cc000)
    /usr/local/go/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8200d3800, 0x7f94cc4fd058, 0xc820144160, 0xc8201cc000)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(_Router).ServeHTTP(0xc820015a90, 0x7f94cc4fd058, 0xc820144160, 0xc8201cc000)
    /home/albertog/go_path/src/github.com/gorilla/mux/mux.go:103 +0x270
net/http.(_ServeMux).ServeHTTP(0xc820010a20, 0x7f94cc4fd058, 0xc820144160, 0xc8201cc000)
    /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc82012c660, 0x7f94cc4fd058, 0xc820144160, 0xc8201cc000)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(_conn).serve(0xc82015a420)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(_Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6

**Comment by mschoch** [comment]
I'm not able to reproduce this, can you let me know the git has for your bleve-explorer and bleve projects, and also the full URL of the HTTP request that caused the panic?

**Comment by mschoch** [comment]
I've tested the fix from @steveyen and can no longer reproduce this issue.  Please try again with latest code.
